### ISSUE TITLE
Tag position change after update.

### ISSUE THREAD

**Issue by Pinkal7600** [harsh159357/InstaTag#1]
When we first add **TAG**  in view and save that **TAG**. After that when we use same x and y coordinate it's added perfect on view but when we again save that **TAG** x and y position is been changed.

 E.g:
        X: 24 and Y: 929 while **TAG** is added. But when we save X: -40.0 and Y: 913.0

Adding TAG method is **"addTag(int x, int y, String tagText, String userId)"** and save TAG method is **"getListOfTagsToBeTagged()"**

**Comment by harsh159357** [comment]
Thanks for reporting out this issue.
It was there in this library from the start.
It will be solved.
But It will take some time as I used to work on this library in spare time.
Not possible before 15 September.

**Comment by harsh159357** [comment]
Thanks for reporting out this issue.
It was there in this library from the start.
It will be solved.
But It will take some time as I used to work on this library in spare time.

**Comment by Pinkal7600** [comment]
@harsh159357 Thanks for your replay.

Can you give me any idea about that x and y changes on update, So I can try to resolve it.

**Comment by harsh159357** [comment]
@Pinkal7600 

Just see the method **addTag()** in **InstaTag.java** watch out for Line no **581 - 585**. This is the logic to add a tag in the view in the specific position.

There is on more major logic which is as follows -

Each Image is Contained in a View(InstaTag) which is having some height and width.

For Example InstaTag **height = 500** and **width=300**

And you have one  tag inside Instatag with coordinates  **x,y(125,227)**

So while saving this tag I am storing its percentage not coordinates so the tag will be at the same position for every device with different screen sizes.

While Storing Tag in DB or SharedPreference X and Y Coordinate for a Tag is stored as follows -

X_Coordinate = (X_Coordinate / InstaTag Width) * 100 (Integer value will be strored)
Y_Coordinate = (Y_Coordinate / InstaTag Height) * 100 (Integer value will be strored)

For our example coordinates 125,227 and Instatag (500,300)
X_Cordinate = 41
Y_Coordinate = 45

But there is a loss in value of coordinates while retrieving the original coordinates -

The logic used while retrieving coordinates from shared preferences or DB is as follows -

X_Coordinate = (X_FromDB * Instag Width)/100  (Integer Value will be used)
Y_Coordinate = (Y_FromDB * Instag Height)/100 (Integer Value will be used)

For our example percentages 41,45 and Instatag (500,300) will become -
X_Cordinate = 123
Y_Coordinate = 225

Which result in loss of position and **addTag()** method is also resulting in Position Loss.

So you just have to consider this above thing while resolving this bug.

If you are able to solve this, please make a pull request it will be very helpful for this library.
I might introduce some more features in this library. Also, I will be able to publish this library also.

**Comment by Pinkal7600** [comment]
I have resolved this bug.

We have to use view.setX() and view.setY() instead of setting view layout parameters. And we have to change that all value which is in the integer to float.

**Comment by harsh159357** [comment]
Can u send the pull request so i can merge those changes.
It will be very helpful for this library 👍.

You can also suggest me some features also 🤔

And Make sure to star this repository if it helped you somewhat 🙂

**Comment by harsh159357** [comment]
Thanks, @Pinkal7600 your insight on Bug resolving helped me a lot. I have used the solution proposed by you and the bug is resolved now. Now tag will be seen at the position where they are saved.

**Comment by bhoomi-shah-itfaq** [comment]
Can you please send me logic for square image?

**Comment by harsh159357** [comment]
@bhoomi-shah-itfaq In creating square image there is not much logic. It is a just a custom view which i have used from already available libraries on github. And how tags are positioned that logic is already described above.
